import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/ui/navbar";
import { MetaMaskContextProvider } from "@/context/useMetaMask";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <MetaMaskContextProvider>
          <Navbar />
          {children}
        </MetaMaskContextProvider>
      </body>


    </html>
  );
}
